### ISSUE TITLE
What Is a Front-End Developer?

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#1]
- Markdown File:  [what-is-a-FD.md](https://github.com/xitu/front-end-handbook-2017/blob/master/what-is-a-FD.md)

**Comment by pobusama** [comment]
认领

**Comment by zhouyao** [comment]
确认 @pobusama  翻译认领

**Comment by pobusama** [comment]
翻译完成，校对完成（从ikcamp迁移）
