### ISSUE TITLE
Front-End Devs Develop For...

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#10]
- Markdown File: [practice/fd-dev-for.md](https://github.com/xitu/front-end-handbook-2017/blob/master/practice/fd-dev-for.md)

**Comment by pobusama** [comment]
认领

**Comment by zhouyao** [comment]
确认 @pobusama 翻译认领

**Comment by pobusama** [comment]
翻译完成 
PR： https://github.com/xitu/front-end-handbook-2017/pull/125

**Comment by pobusama** [comment]
校对修改完成
