### ISSUE TITLE
Learn Multi-Device Dev (e.g., RWD)

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#100]
- Markdown File: [learning/multi-device-dev.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/multi-device-dev.md)

**Comment by MatildaJin** [comment]
认领

**Comment by MatildaJin** [comment]
完成

**Comment by linhe0x0** [comment]
@zhouyao @MatildaJin 这篇文章的状态目前是待校对还是？没看到 PR 地址呐~

**Comment by MatildaJin** [comment]
这篇文章已经翻译完成，等待校对（其实不需要了）。没有PR因为是直接翻译的。这些是我统一翻译完成，因为太短或者内容太简单，所以不让大家认领了，就我直接过滤掉。 @sqrthree

**Comment by linhe0x0** [comment]
好哒~ 那可以 close 了吧？

**Comment by MatildaJin** [comment]
可以可以～ @sqrthree
