### ISSUE TITLE
Front-End on a Team

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#11]
- Markdown File: [practice/team.md](https://github.com/xitu/front-end-handbook-2017/blob/master/practice/team.md)

**Comment by pobusama** [comment]
认领

**Comment by zhouyao** [comment]
确认 @pobusama  翻译认领

**Comment by pobusama** [comment]
翻译完毕，等待校验

**Comment by pobusama** [comment]
校对修改完毕
