### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by ibbatta** [xitu/front-end-handbook-2017#199]
You project sounds great but... what about english translation to being understood by folks?
(I will be grateful eternally)

**Comment by jprojs** [comment]
+1

**Comment by jprojs** [comment]
Hi, 

This project is a fork, if you want read in english, please follow https://github.com/FrontendMasters/front-end-handbook-2017

**Comment by ibbatta** [comment]
Oh ok!! Thanks dude :)
