### ISSUE TITLE
A Call for Translations

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#3]
### 任务列表：

- [待翻译](https://github.com/xitu/front-end-handbook-2017/issues?q=is%3Aissue+is%3Aopen+label%3A%E7%BF%BB%E8%AF%91%E8%AE%A4%E9%A2%86)
- [待校对](https://github.com/xitu/front-end-handbook-2017/labels/%E6%A0%A1%E5%AF%B9%E8%AE%A4%E9%A2%86)

### 注意：

- 我们会在推广时添加译者和校对者信息。
- 每篇文章至少需要一个校对、最多两个校对参与。
- 认领相关任务请在对应的 Issue 下回复认领的任务类型：`申请翻译`、`申请校对`
- 申请通过之后可选择对应的文章进行翻译，翻译完成之后发起 PR。
- 可同时申请多篇任务，但是请注意每篇文章均在独立的新分支上完成， 要求每个 PR 只能含有一篇译文。
- 翻译时请遵循 [排版要求](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)
- 校对时请参考 [参与校对的正确姿势](https://github.com/xitu/gold-miner/wiki/%E5%8F%82%E4%B8%8E%E6%A0%A1%E5%AF%B9%E7%9A%84%E6%AD%A3%E7%A1%AE%E5%A7%BF%E5%8A%BF)
- [校对任务的具体内容都有哪些](https://github.com/xitu/gold-miner/wiki/%E5%8D%81%E4%B8%87%E4%B8%AA%E4%B8%BA%E4%BB%80%E4%B9%88#%E6%A0%A1%E5%AF%B9%E4%BB%BB%E5%8A%A1%E7%9A%84%E5%85%B7%E4%BD%93%E5%86%85%E5%AE%B9%E9%83%BD%E6%9C%89%E5%93%AA%E4%BA%9B)

**Comment by aladdin-add** [comment]
待校对的链接不对。

**Comment by linhe0x0** [comment]
哈哈~ 本来是想着目前没有待校对的文章，就没加链接，不过现在已经更新上了。
