### ISSUE TITLE
Part III: Front-End Dev Tools

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#33]
- Markdown File: [tools.md](https://github.com/xitu/front-end-handbook-2017/blob/master/tools.md)

**Comment by cfancc** [comment]
认领翻译

**Comment by linhe0x0** [comment]
@zhouyao

**Comment by MatildaJin** [comment]
confirm application @cfanlife @sqrthree

**Comment by pobusama** [comment]
校对完毕
