### ISSUE TITLE
Static Site Generators Tools

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#37]
- Markdown File: [tools/static.md](https://github.com/xitu/front-end-handbook-2017/blob/master/tools/static.md)

**Comment by MatildaJin** [comment]
完成

**Comment by linhe0x0** [comment]
@MatildaJin 我之前创建 Issue 的时候，是用脚本跑出来的，所以这些篇幅较少的部分，没有进行过滤，如果你翻译完了之后直接发个 PR，然后把这个 close 掉就好啦。
