### ISSUE TITLE
Recap of Front-end Dev in 2016

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#4]
- Markdonw File: [recap.md](https://github.com/xitu/front-end-handbook-2017/blob/master/recap.md)

**Comment by pobusama** [comment]
认领

**Comment by zhouyao** [comment]
确认 @pobusama  翻译认领

**Comment by pobusama** [comment]
翻译完成，校对完成（从ikcamp迁移）
