### ISSUE TITLE
Learn DNS

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#40]
- Markdown File: [learning/dns.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/dns.md)

**Comment by pobusama** [comment]
认领

**Comment by MatildaJin** [comment]
确认

**Comment by pobusama** [comment]
翻译完成：https://github.com/xitu/front-end-handbook-2017/pull/143

**Comment by pobusama** [comment]
校对后修改完毕
