### ISSUE TITLE
Newsletters, News, & Podcasts

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#41]
- Markdown File: [learning/news-podcasts.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/news-podcasts.md)

**Comment by pobusama** [comment]
认领

**Comment by MatildaJin** [comment]
确认

**Comment by pobusama** [comment]
翻译完毕

**Comment by pobusama** [comment]
校对修改完毕
