### ISSUE TITLE
Learn HTTP/Networks

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#45]
- Markdown File: [learning/http-networks.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/http-networks.md)

**Comment by DDU1222** [comment]
认领翻译

**Comment by DDU1222** [comment]
确认认领

**Comment by MatildaJin** [comment]
确认认领@DDU1222

**Comment by DDU1222** [comment]
翻译完成 https://github.com/xitu/front-end-handbook-2017/pull/117

**Comment by cfancc** [comment]
校对完成
