### ISSUE TITLE
Learn Web Browsers

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#46]
- Markdown File: [learning/browsers.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/browsers.md)

**Comment by DDU1222** [comment]
确认认领

**Comment by MatildaJin** [comment]
confirm application@DDU1222

**Comment by DDU1222** [comment]
翻译完成 https://github.com/xitu/front-end-handbook-2017/pull/128

**Comment by cfancc** [comment]
校对完成 @DDU1222 @MatildaJin
