### ISSUE TITLE
How FDs Are Made

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#55]
- Markdown File: [practice/making-fd.md](https://github.com/xitu/front-end-handbook-2017/blob/master/practice/making-fd.md)

**Comment by pobusama** [comment]
认领

**Comment by pobusama** [comment]
翻译完毕 https://github.com/xitu/front-end-handbook-2017/pull/142

**Comment by MatildaJin** [comment]
确认

**Comment by pobusama** [comment]
校对后修改完毕
