### ISSUE TITLE
Front-End Jobs Titles

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#7]
- Markdown File: [types-of-front-end-dev.md](https://github.com/xitu/front-end-handbook-2017/blob/master/practice/types-of-front-end-dev.md)

**Comment by pobusama** [comment]
认领

**Comment by zhouyao** [comment]
确认 @pobusama  翻译认领

**Comment by pobusama** [comment]
翻译完成，待校对

**Comment by pobusama** [comment]
修改完成
