### ISSUE TITLE
Learn SEO

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#77]
- Markdown File: [learning/seo.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/seo.md)

**Comment by xunge0613** [comment]
萌新来申请翻译啦 …… 感觉这一系列很适合萌新来练手呢…… @sqrthree

**Comment by yanyixin** [comment]
翻译认领

**Comment by MatildaJin** [comment]
确认认领@yanyixin

**Comment by yanyixin** [comment]
翻译完成 #114

**Comment by yanyixin** [comment]
请@MatildaJin @cfanlife 校对

**Comment by cfancc** [comment]
认领校对

**Comment by MatildaJin** [comment]
认领校对

**Comment by cfancc** [comment]
校对完成 @yanyixin
