### ISSUE TITLE
JavaScript Tools

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#85]
- Markdown File: [tools/js.md](https://github.com/xitu/front-end-handbook-2017/blob/master/tools/js.md)

**Comment by pobusama** [comment]
认领

**Comment by pobusama** [comment]
翻译完毕 https://github.com/xitu/front-end-handbook-2017/pull/141

**Comment by MatildaJin** [comment]
确认。。。

**Comment by pobusama** [comment]
校对修改完毕
