### ISSUE TITLE
Browser Tools

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#88]
- Markdown File: [tools/browser.md](https://github.com/xitu/front-end-handbook-2017/blob/master/tools/browser.md)

**Comment by BruceCham** [comment]
翻译认领

**Comment by MatildaJin** [comment]
确认

**Comment by BruceCham** [comment]
[申请校对](https://github.com/xitu/front-end-handbook-2017/pull/154/files)

**Comment by cfancc** [comment]
校对完成
