### ISSUE TITLE
Learn Web Dev Tools

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#89]
- Markdown File: [learning/browser-dev-tools.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/browser-dev-tools.md)

**Comment by BruceCham** [comment]
翻译认领

**Comment by MatildaJin** [comment]
确认

**Comment by BruceCham** [comment]
[申请校对](https://github.com/xitu/front-end-handbook-2017/pull/154/files) @MatildaJin
