### ISSUE TITLE
Front-End Dev Skills

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#9]
- Markdown File: [practice/skills.md](https://github.com/xitu/front-end-handbook-2017/blob/master/practice/skills.md)

**Comment by DDU1222** [comment]
确认认领

**Comment by MatildaJin** [comment]
confirm application@DDU1222

**Comment by DDU1222** [comment]
翻译完成  https://github.com/xitu/front-end-handbook-2017/pull/116
