### ISSUE TITLE
Learn Version Control

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#91]
- Markdown File: [learning/version-control.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/version-control.md)

**Comment by blueken** [comment]
认领

**Comment by MatildaJin** [comment]
确认认领@blueken

**Comment by blueken** [comment]
申请校对 https://github.com/xitu/front-end-handbook-2017/pull/122
