### ISSUE TITLE
Learn JavaScript

### ISSUE THREAD

**Issue by linhe0x0** [xitu/front-end-handbook-2017#92]
- Markdown File: [learning/javascript.md](https://github.com/xitu/front-end-handbook-2017/blob/master/learning/javascript.md)

**Comment by MAYDAY1993** [comment]
认领

**Comment by MatildaJin** [comment]
确认认领@MAYDAY1993

**Comment by linhe0x0** [comment]
@MAYDAY1993 咦，小姐姐好久不见啦，你也是沪江的呀 :stuck_out_tongue_winking_eye:

**Comment by MAYDAY1993** [comment]
@sqrthree 请叫我迷妹 嗯 咦 评论里怎么加表情 哦 上次的坑我这礼拜抓紧填 小哥不要打我
